package com.mrcrayfish.furniture.integration.biomesoplenty;

import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;

import com.mrcrayfish.furniture.blocks.*;
import com.mrcrayfish.furniture.init.FurnitureBlocks;
import com.mrcrayfish.furniture.items.ItemCrate;
import com.mrcrayfish.furniture.items.ItemHedge;
import com.mrcrayfish.furniture.items.ItemUpgradedGate;

public class FurnitureBlocksBOP
{
    public static final Block HEDGE_BIOMESOPLENTY_CHERRY, HEDGE_BIOMESOPLENTY_EBONY, HEDGE_BIOMESOPLENTY_ETHEREAL, HEDGE_BIOMESOPLENTY_EUCALYPTUS, HEDGE_BIOMESOPLENTY_FIR, HEDGE_BIOMESOPLENTY_HELLBARK, HEDGE_BIOMESOPLENTY_JACARANDA, HEDGE_BIOMESOPLENTY_MAGIC, HEDGE_BIOMESOPLENTY_MAHOGANY, HEDGE_BIOMESOPLENTY_MANGROVE, HEDGE_BIOMESOPLENTY_PALM, HEDGE_BIOMESOPLENTY_PINE, HEDGE_BIOMESOPLENTY_REDWOOD, HEDGE_BIOMESOPLENTY_SACRED_OAK, HEDGE_BIOMESOPLENTY_UMBRAN, HEDGE_BIOMESOPLENTY_WILLOW;
    public static final Block COFFEE_TABLE_BIOMESOPLENTY_CHERRY, COFFEE_TABLE_BIOMESOPLENTY_EBONY, COFFEE_TABLE_BIOMESOPLENTY_ETHEREAL, COFFEE_TABLE_BIOMESOPLENTY_EUCALYPTUS, COFFEE_TABLE_BIOMESOPLENTY_FIR, COFFEE_TABLE_BIOMESOPLENTY_HELLBARK, COFFEE_TABLE_BIOMESOPLENTY_JACARANDA, COFFEE_TABLE_BIOMESOPLENTY_MAGIC, COFFEE_TABLE_BIOMESOPLENTY_MAHOGANY, COFFEE_TABLE_BIOMESOPLENTY_MANGROVE, COFFEE_TABLE_BIOMESOPLENTY_PALM, COFFEE_TABLE_BIOMESOPLENTY_PINE, COFFEE_TABLE_BIOMESOPLENTY_REDWOOD, COFFEE_TABLE_BIOMESOPLENTY_SACRED_OAK, COFFEE_TABLE_BIOMESOPLENTY_UMBRAN, COFFEE_TABLE_BIOMESOPLENTY_WILLOW;
    public static final Block CHAIR_BIOMESOPLENTY_CHERRY, CHAIR_BIOMESOPLENTY_EBONY, CHAIR_BIOMESOPLENTY_ETHEREAL, CHAIR_BIOMESOPLENTY_EUCALYPTUS, CHAIR_BIOMESOPLENTY_FIR, CHAIR_BIOMESOPLENTY_HELLBARK, CHAIR_BIOMESOPLENTY_JACARANDA, CHAIR_BIOMESOPLENTY_MAGIC, CHAIR_BIOMESOPLENTY_MAHOGANY, CHAIR_BIOMESOPLENTY_MANGROVE, CHAIR_BIOMESOPLENTY_PALM, CHAIR_BIOMESOPLENTY_PINE, CHAIR_BIOMESOPLENTY_REDWOOD, CHAIR_BIOMESOPLENTY_SACRED_OAK, CHAIR_BIOMESOPLENTY_UMBRAN, CHAIR_BIOMESOPLENTY_WILLOW;
    public static final Block TABLE_BIOMESOPLENTY_CHERRY, TABLE_BIOMESOPLENTY_EBONY, TABLE_BIOMESOPLENTY_ETHEREAL, TABLE_BIOMESOPLENTY_EUCALYPTUS, TABLE_BIOMESOPLENTY_FIR, TABLE_BIOMESOPLENTY_HELLBARK, TABLE_BIOMESOPLENTY_JACARANDA, TABLE_BIOMESOPLENTY_MAGIC, TABLE_BIOMESOPLENTY_MAHOGANY, TABLE_BIOMESOPLENTY_MANGROVE, TABLE_BIOMESOPLENTY_PALM, TABLE_BIOMESOPLENTY_PINE, TABLE_BIOMESOPLENTY_REDWOOD, TABLE_BIOMESOPLENTY_SACRED_OAK, TABLE_BIOMESOPLENTY_UMBRAN, TABLE_BIOMESOPLENTY_WILLOW;
    public static final Block CABINET_BIOMESOPLENTY_CHERRY, CABINET_BIOMESOPLENTY_EBONY, CABINET_BIOMESOPLENTY_ETHEREAL, CABINET_BIOMESOPLENTY_EUCALYPTUS, CABINET_BIOMESOPLENTY_FIR, CABINET_BIOMESOPLENTY_HELLBARK, CABINET_BIOMESOPLENTY_JACARANDA, CABINET_BIOMESOPLENTY_MAGIC, CABINET_BIOMESOPLENTY_MAHOGANY, CABINET_BIOMESOPLENTY_MANGROVE, CABINET_BIOMESOPLENTY_PALM, CABINET_BIOMESOPLENTY_PINE, CABINET_BIOMESOPLENTY_REDWOOD, CABINET_BIOMESOPLENTY_SACRED_OAK, CABINET_BIOMESOPLENTY_UMBRAN, CABINET_BIOMESOPLENTY_WILLOW;
    public static final Block BEDSIDE_CABINET_BIOMESOPLENTY_CHERRY, BEDSIDE_CABINET_BIOMESOPLENTY_EBONY, BEDSIDE_CABINET_BIOMESOPLENTY_ETHEREAL, BEDSIDE_CABINET_BIOMESOPLENTY_EUCALYPTUS, BEDSIDE_CABINET_BIOMESOPLENTY_FIR, BEDSIDE_CABINET_BIOMESOPLENTY_HELLBARK, BEDSIDE_CABINET_BIOMESOPLENTY_JACARANDA, BEDSIDE_CABINET_BIOMESOPLENTY_MAGIC, BEDSIDE_CABINET_BIOMESOPLENTY_MAHOGANY, BEDSIDE_CABINET_BIOMESOPLENTY_MANGROVE, BEDSIDE_CABINET_BIOMESOPLENTY_PALM, BEDSIDE_CABINET_BIOMESOPLENTY_PINE, BEDSIDE_CABINET_BIOMESOPLENTY_REDWOOD, BEDSIDE_CABINET_BIOMESOPLENTY_SACRED_OAK, BEDSIDE_CABINET_BIOMESOPLENTY_UMBRAN, BEDSIDE_CABINET_BIOMESOPLENTY_WILLOW;
    public static final Block DESK_BIOMESOPLENTY_CHERRY, DESK_BIOMESOPLENTY_EBONY, DESK_BIOMESOPLENTY_ETHEREAL, DESK_BIOMESOPLENTY_EUCALYPTUS, DESK_BIOMESOPLENTY_FIR, DESK_BIOMESOPLENTY_HELLBARK, DESK_BIOMESOPLENTY_JACARANDA, DESK_BIOMESOPLENTY_MAGIC, DESK_BIOMESOPLENTY_MAHOGANY, DESK_BIOMESOPLENTY_MANGROVE, DESK_BIOMESOPLENTY_PALM, DESK_BIOMESOPLENTY_PINE, DESK_BIOMESOPLENTY_REDWOOD, DESK_BIOMESOPLENTY_SACRED_OAK, DESK_BIOMESOPLENTY_UMBRAN, DESK_BIOMESOPLENTY_WILLOW;
    public static final Block DESK_CABINET_BIOMESOPLENTY_CHERRY, DESK_CABINET_BIOMESOPLENTY_EBONY, DESK_CABINET_BIOMESOPLENTY_ETHEREAL, DESK_CABINET_BIOMESOPLENTY_EUCALYPTUS, DESK_CABINET_BIOMESOPLENTY_FIR, DESK_CABINET_BIOMESOPLENTY_HELLBARK, DESK_CABINET_BIOMESOPLENTY_JACARANDA, DESK_CABINET_BIOMESOPLENTY_MAGIC, DESK_CABINET_BIOMESOPLENTY_MAHOGANY, DESK_CABINET_BIOMESOPLENTY_MANGROVE, DESK_CABINET_BIOMESOPLENTY_PALM, DESK_CABINET_BIOMESOPLENTY_PINE, DESK_CABINET_BIOMESOPLENTY_REDWOOD, DESK_CABINET_BIOMESOPLENTY_SACRED_OAK, DESK_CABINET_BIOMESOPLENTY_UMBRAN, DESK_CABINET_BIOMESOPLENTY_WILLOW;
    public static final Block MAIL_BOX_BIOMESOPLENTY_CHERRY, MAIL_BOX_BIOMESOPLENTY_EBONY, MAIL_BOX_BIOMESOPLENTY_ETHEREAL, MAIL_BOX_BIOMESOPLENTY_EUCALYPTUS, MAIL_BOX_BIOMESOPLENTY_FIR, MAIL_BOX_BIOMESOPLENTY_HELLBARK, MAIL_BOX_BIOMESOPLENTY_JACARANDA, MAIL_BOX_BIOMESOPLENTY_MAGIC, MAIL_BOX_BIOMESOPLENTY_MAHOGANY, MAIL_BOX_BIOMESOPLENTY_MANGROVE, MAIL_BOX_BIOMESOPLENTY_PALM, MAIL_BOX_BIOMESOPLENTY_PINE, MAIL_BOX_BIOMESOPLENTY_REDWOOD, MAIL_BOX_BIOMESOPLENTY_SACRED_OAK, MAIL_BOX_BIOMESOPLENTY_UMBRAN, MAIL_BOX_BIOMESOPLENTY_WILLOW;
    public static final Block DOOR_BELL_BIOMESOPLENTY_CHERRY, DOOR_BELL_BIOMESOPLENTY_EBONY, DOOR_BELL_BIOMESOPLENTY_ETHEREAL, DOOR_BELL_BIOMESOPLENTY_EUCALYPTUS, DOOR_BELL_BIOMESOPLENTY_FIR, DOOR_BELL_BIOMESOPLENTY_HELLBARK, DOOR_BELL_BIOMESOPLENTY_JACARANDA, DOOR_BELL_BIOMESOPLENTY_MAGIC, DOOR_BELL_BIOMESOPLENTY_MAHOGANY, DOOR_BELL_BIOMESOPLENTY_MANGROVE, DOOR_BELL_BIOMESOPLENTY_PALM, DOOR_BELL_BIOMESOPLENTY_PINE, DOOR_BELL_BIOMESOPLENTY_REDWOOD, DOOR_BELL_BIOMESOPLENTY_SACRED_OAK, DOOR_BELL_BIOMESOPLENTY_UMBRAN, DOOR_BELL_BIOMESOPLENTY_WILLOW;
    public static final Block CRATE_BIOMESOPLENTY_CHERRY, CRATE_BIOMESOPLENTY_EBONY, CRATE_BIOMESOPLENTY_ETHEREAL, CRATE_BIOMESOPLENTY_EUCALYPTUS, CRATE_BIOMESOPLENTY_FIR, CRATE_BIOMESOPLENTY_HELLBARK, CRATE_BIOMESOPLENTY_JACARANDA, CRATE_BIOMESOPLENTY_MAGIC, CRATE_BIOMESOPLENTY_MAHOGANY, CRATE_BIOMESOPLENTY_MANGROVE, CRATE_BIOMESOPLENTY_PALM, CRATE_BIOMESOPLENTY_PINE, CRATE_BIOMESOPLENTY_REDWOOD, CRATE_BIOMESOPLENTY_SACRED_OAK, CRATE_BIOMESOPLENTY_UMBRAN, CRATE_BIOMESOPLENTY_WILLOW;
    public static final Block BLINDS_BIOMESOPLENTY_CHERRY, BLINDS_BIOMESOPLENTY_EBONY, BLINDS_BIOMESOPLENTY_ETHEREAL, BLINDS_BIOMESOPLENTY_EUCALYPTUS, BLINDS_BIOMESOPLENTY_FIR, BLINDS_BIOMESOPLENTY_HELLBARK, BLINDS_BIOMESOPLENTY_JACARANDA, BLINDS_BIOMESOPLENTY_MAGIC, BLINDS_BIOMESOPLENTY_MAHOGANY, BLINDS_BIOMESOPLENTY_MANGROVE, BLINDS_BIOMESOPLENTY_PALM, BLINDS_BIOMESOPLENTY_PINE, BLINDS_BIOMESOPLENTY_REDWOOD, BLINDS_BIOMESOPLENTY_SACRED_OAK, BLINDS_BIOMESOPLENTY_UMBRAN, BLINDS_BIOMESOPLENTY_WILLOW;
    public static final Block BLINDS_BIOMESOPLENTY_CHERRY_CLOSED, BLINDS_BIOMESOPLENTY_EBONY_CLOSED, BLINDS_BIOMESOPLENTY_ETHEREAL_CLOSED, BLINDS_BIOMESOPLENTY_EUCALYPTUS_CLOSED, BLINDS_BIOMESOPLENTY_FIR_CLOSED, BLINDS_BIOMESOPLENTY_HELLBARK_CLOSED, BLINDS_BIOMESOPLENTY_JACARANDA_CLOSED, BLINDS_BIOMESOPLENTY_MAGIC_CLOSED, BLINDS_BIOMESOPLENTY_MAHOGANY_CLOSED, BLINDS_BIOMESOPLENTY_MANGROVE_CLOSED, BLINDS_BIOMESOPLENTY_PALM_CLOSED, BLINDS_BIOMESOPLENTY_PINE_CLOSED, BLINDS_BIOMESOPLENTY_REDWOOD_CLOSED, BLINDS_BIOMESOPLENTY_SACRED_OAK_CLOSED, BLINDS_BIOMESOPLENTY_UMBRAN_CLOSED, BLINDS_BIOMESOPLENTY_WILLOW_CLOSED;
    public static final Block FENCE_UPGRADED_BIOMESOPLENTY_CHERRY, FENCE_UPGRADED_BIOMESOPLENTY_EBONY, FENCE_UPGRADED_BIOMESOPLENTY_ETHEREAL, FENCE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS, FENCE_UPGRADED_BIOMESOPLENTY_FIR, FENCE_UPGRADED_BIOMESOPLENTY_HELLBARK, FENCE_UPGRADED_BIOMESOPLENTY_JACARANDA, FENCE_UPGRADED_BIOMESOPLENTY_MAGIC, FENCE_UPGRADED_BIOMESOPLENTY_MAHOGANY, FENCE_UPGRADED_BIOMESOPLENTY_MANGROVE, FENCE_UPGRADED_BIOMESOPLENTY_PALM, FENCE_UPGRADED_BIOMESOPLENTY_PINE, FENCE_UPGRADED_BIOMESOPLENTY_REDWOOD, FENCE_UPGRADED_BIOMESOPLENTY_SACRED_OAK, FENCE_UPGRADED_BIOMESOPLENTY_UMBRAN, FENCE_UPGRADED_BIOMESOPLENTY_WILLOW;
    public static final Block GATE_UPGRADED_BIOMESOPLENTY_CHERRY, GATE_UPGRADED_BIOMESOPLENTY_EBONY, GATE_UPGRADED_BIOMESOPLENTY_ETHEREAL, GATE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS, GATE_UPGRADED_BIOMESOPLENTY_FIR, GATE_UPGRADED_BIOMESOPLENTY_HELLBARK, GATE_UPGRADED_BIOMESOPLENTY_JACARANDA, GATE_UPGRADED_BIOMESOPLENTY_MAGIC, GATE_UPGRADED_BIOMESOPLENTY_MAHOGANY, GATE_UPGRADED_BIOMESOPLENTY_MANGROVE, GATE_UPGRADED_BIOMESOPLENTY_PALM, GATE_UPGRADED_BIOMESOPLENTY_PINE, GATE_UPGRADED_BIOMESOPLENTY_REDWOOD, GATE_UPGRADED_BIOMESOPLENTY_SACRED_OAK, GATE_UPGRADED_BIOMESOPLENTY_UMBRAN, GATE_UPGRADED_BIOMESOPLENTY_WILLOW;
    public static final Block PARK_BENCH_BIOMESOPLENTY_CHERRY, PARK_BENCH_BIOMESOPLENTY_EBONY, PARK_BENCH_BIOMESOPLENTY_ETHEREAL, PARK_BENCH_BIOMESOPLENTY_EUCALYPTUS, PARK_BENCH_BIOMESOPLENTY_FIR, PARK_BENCH_BIOMESOPLENTY_HELLBARK, PARK_BENCH_BIOMESOPLENTY_JACARANDA, PARK_BENCH_BIOMESOPLENTY_MAGIC, PARK_BENCH_BIOMESOPLENTY_MAHOGANY, PARK_BENCH_BIOMESOPLENTY_MANGROVE, PARK_BENCH_BIOMESOPLENTY_PALM, PARK_BENCH_BIOMESOPLENTY_PINE, PARK_BENCH_BIOMESOPLENTY_REDWOOD, PARK_BENCH_BIOMESOPLENTY_SACRED_OAK, PARK_BENCH_BIOMESOPLENTY_UMBRAN, PARK_BENCH_BIOMESOPLENTY_WILLOW;

    static
    {
        HEDGE_BIOMESOPLENTY_CHERRY = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_cherry").setRegistryName("hedge_biomesoplenty_cherry");
        HEDGE_BIOMESOPLENTY_EBONY = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_ebony").setRegistryName("hedge_biomesoplenty_ebony");
        HEDGE_BIOMESOPLENTY_ETHEREAL = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_ethereal").setRegistryName("hedge_biomesoplenty_ethereal");
        HEDGE_BIOMESOPLENTY_EUCALYPTUS = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_eucalyptus").setRegistryName("hedge_biomesoplenty_eucalyptus");
        HEDGE_BIOMESOPLENTY_FIR = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_fir").setRegistryName("hedge_biomesoplenty_fir");
        HEDGE_BIOMESOPLENTY_HELLBARK = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_hellbark").setRegistryName("hedge_biomesoplenty_hellbark");
        HEDGE_BIOMESOPLENTY_JACARANDA = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_jacaranda").setRegistryName("hedge_biomesoplenty_jacaranda");
        HEDGE_BIOMESOPLENTY_MAGIC = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_magic").setRegistryName("hedge_biomesoplenty_magic");
        HEDGE_BIOMESOPLENTY_MAHOGANY = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_mahogany").setRegistryName("hedge_biomesoplenty_mahogany");
        HEDGE_BIOMESOPLENTY_MANGROVE = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_mangrove").setRegistryName("hedge_biomesoplenty_mangrove");
        HEDGE_BIOMESOPLENTY_PALM = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_palm").setRegistryName("hedge_biomesoplenty_palm");
        HEDGE_BIOMESOPLENTY_PINE = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_pine").setRegistryName("hedge_biomesoplenty_pine");
        HEDGE_BIOMESOPLENTY_REDWOOD = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_redwood").setRegistryName("hedge_biomesoplenty_redwood");
        HEDGE_BIOMESOPLENTY_SACRED_OAK = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_sacred_oak").setRegistryName("hedge_biomesoplenty_sacred_oak");
        HEDGE_BIOMESOPLENTY_UMBRAN = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_umbran").setRegistryName("hedge_biomesoplenty_umbran");
        HEDGE_BIOMESOPLENTY_WILLOW = new BlockHedge().setUnlocalizedName("hedge_biomesoplenty_willow").setRegistryName("hedge_biomesoplenty_willow");

        COFFEE_TABLE_BIOMESOPLENTY_CHERRY = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_cherry");
        COFFEE_TABLE_BIOMESOPLENTY_EBONY = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_ebony");
        COFFEE_TABLE_BIOMESOPLENTY_ETHEREAL = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_ethereal");
        COFFEE_TABLE_BIOMESOPLENTY_EUCALYPTUS = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_eucalyptus");
        COFFEE_TABLE_BIOMESOPLENTY_FIR = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_fir");
        COFFEE_TABLE_BIOMESOPLENTY_HELLBARK = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_hellbark");
        COFFEE_TABLE_BIOMESOPLENTY_JACARANDA = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_jacaranda");
        COFFEE_TABLE_BIOMESOPLENTY_MAGIC = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_magic");
        COFFEE_TABLE_BIOMESOPLENTY_MAHOGANY = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_mahogany");
        COFFEE_TABLE_BIOMESOPLENTY_MANGROVE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_mangrove");
        COFFEE_TABLE_BIOMESOPLENTY_PALM = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_palm");
        COFFEE_TABLE_BIOMESOPLENTY_PINE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_pine");
        COFFEE_TABLE_BIOMESOPLENTY_REDWOOD = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_redwood");
        COFFEE_TABLE_BIOMESOPLENTY_SACRED_OAK = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_sacred_oak");
        COFFEE_TABLE_BIOMESOPLENTY_UMBRAN = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_umbran");
        COFFEE_TABLE_BIOMESOPLENTY_WILLOW = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_biomesoplenty_willow");

        CHAIR_BIOMESOPLENTY_CHERRY = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_cherry").setRegistryName("chair_biomesoplenty_cherry");
        CHAIR_BIOMESOPLENTY_EBONY = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_ebony").setRegistryName("chair_biomesoplenty_ebony");
        CHAIR_BIOMESOPLENTY_ETHEREAL = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_ethereal").setRegistryName("chair_biomesoplenty_ethereal");
        CHAIR_BIOMESOPLENTY_EUCALYPTUS = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_eucalyptus").setRegistryName("chair_biomesoplenty_eucalyptus");
        CHAIR_BIOMESOPLENTY_FIR = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_fir").setRegistryName("chair_biomesoplenty_fir");
        CHAIR_BIOMESOPLENTY_HELLBARK = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_hellbark").setRegistryName("chair_biomesoplenty_hellbark");
        CHAIR_BIOMESOPLENTY_JACARANDA = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_jacaranda").setRegistryName("chair_biomesoplenty_jacaranda");
        CHAIR_BIOMESOPLENTY_MAGIC = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_magic").setRegistryName("chair_biomesoplenty_magic");
        CHAIR_BIOMESOPLENTY_MAHOGANY = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_mahogany").setRegistryName("chair_biomesoplenty_mahogany");
        CHAIR_BIOMESOPLENTY_MANGROVE = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_mangrove").setRegistryName("chair_biomesoplenty_mangrove");
        CHAIR_BIOMESOPLENTY_PALM = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_palm").setRegistryName("chair_biomesoplenty_palm");
        CHAIR_BIOMESOPLENTY_PINE = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_pine").setRegistryName("chair_biomesoplenty_pine");
        CHAIR_BIOMESOPLENTY_REDWOOD = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_redwood").setRegistryName("chair_biomesoplenty_redwood");
        CHAIR_BIOMESOPLENTY_SACRED_OAK = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_sacred_oak").setRegistryName("chair_biomesoplenty_sacred_oak");
        CHAIR_BIOMESOPLENTY_UMBRAN = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_umbran").setRegistryName("chair_biomesoplenty_umbran");
        CHAIR_BIOMESOPLENTY_WILLOW = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_biomesoplenty_willow").setRegistryName("chair_biomesoplenty_willow");

        TABLE_BIOMESOPLENTY_CHERRY = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_cherry").setRegistryName("table_biomesoplenty_cherry");
        TABLE_BIOMESOPLENTY_EBONY = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_ebony").setRegistryName("table_biomesoplenty_ebony");
        TABLE_BIOMESOPLENTY_ETHEREAL = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_ethereal").setRegistryName("table_biomesoplenty_ethereal");
        TABLE_BIOMESOPLENTY_EUCALYPTUS = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_eucalyptus").setRegistryName("table_biomesoplenty_eucalyptus");
        TABLE_BIOMESOPLENTY_FIR = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_fir").setRegistryName("table_biomesoplenty_fir");
        TABLE_BIOMESOPLENTY_HELLBARK = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_hellbark").setRegistryName("table_biomesoplenty_hellbark");
        TABLE_BIOMESOPLENTY_JACARANDA = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_jacaranda").setRegistryName("table_biomesoplenty_jacaranda");
        TABLE_BIOMESOPLENTY_MAGIC = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_magic").setRegistryName("table_biomesoplenty_magic");
        TABLE_BIOMESOPLENTY_MAHOGANY = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_mahogany").setRegistryName("table_biomesoplenty_mahogany");
        TABLE_BIOMESOPLENTY_MANGROVE = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_mangrove").setRegistryName("table_biomesoplenty_mangrove");
        TABLE_BIOMESOPLENTY_PALM = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_palm").setRegistryName("table_biomesoplenty_palm");
        TABLE_BIOMESOPLENTY_PINE = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_pine").setRegistryName("table_biomesoplenty_pine");
        TABLE_BIOMESOPLENTY_REDWOOD = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_redwood").setRegistryName("table_biomesoplenty_redwood");
        TABLE_BIOMESOPLENTY_SACRED_OAK = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_sacred_oak").setRegistryName("table_biomesoplenty_sacred_oak");
        TABLE_BIOMESOPLENTY_UMBRAN = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_umbran").setRegistryName("table_biomesoplenty_umbran");
        TABLE_BIOMESOPLENTY_WILLOW = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_biomesoplenty_willow").setRegistryName("table_biomesoplenty_willow");

        CABINET_BIOMESOPLENTY_CHERRY = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_cherry").setRegistryName("cabinet_biomesoplenty_cherry");
        CABINET_BIOMESOPLENTY_EBONY = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_ebony").setRegistryName("cabinet_biomesoplenty_ebony");
        CABINET_BIOMESOPLENTY_ETHEREAL = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_ethereal").setRegistryName("cabinet_biomesoplenty_ethereal");
        CABINET_BIOMESOPLENTY_EUCALYPTUS = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_eucalyptus").setRegistryName("cabinet_biomesoplenty_eucalyptus");
        CABINET_BIOMESOPLENTY_FIR = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_fir").setRegistryName("cabinet_biomesoplenty_fir");
        CABINET_BIOMESOPLENTY_HELLBARK = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_hellbark").setRegistryName("cabinet_biomesoplenty_hellbark");
        CABINET_BIOMESOPLENTY_JACARANDA = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_jacaranda").setRegistryName("cabinet_biomesoplenty_jacaranda");
        CABINET_BIOMESOPLENTY_MAGIC = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_magic").setRegistryName("cabinet_biomesoplenty_magic");
        CABINET_BIOMESOPLENTY_MAHOGANY = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_mahogany").setRegistryName("cabinet_biomesoplenty_mahogany");
        CABINET_BIOMESOPLENTY_MANGROVE = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_mangrove").setRegistryName("cabinet_biomesoplenty_mangrove");
        CABINET_BIOMESOPLENTY_PALM = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_palm").setRegistryName("cabinet_biomesoplenty_palm");
        CABINET_BIOMESOPLENTY_PINE = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_pine").setRegistryName("cabinet_biomesoplenty_pine");
        CABINET_BIOMESOPLENTY_REDWOOD = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_redwood").setRegistryName("cabinet_biomesoplenty_redwood");
        CABINET_BIOMESOPLENTY_SACRED_OAK = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_sacred_oak").setRegistryName("cabinet_biomesoplenty_sacred_oak");
        CABINET_BIOMESOPLENTY_UMBRAN = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_umbran").setRegistryName("cabinet_biomesoplenty_umbran");
        CABINET_BIOMESOPLENTY_WILLOW = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_biomesoplenty_willow").setRegistryName("cabinet_biomesoplenty_willow");

        BEDSIDE_CABINET_BIOMESOPLENTY_CHERRY = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_cherry").setRegistryName("bedside_cabinet_biomesoplenty_cherry");
        BEDSIDE_CABINET_BIOMESOPLENTY_EBONY = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_ebony").setRegistryName("bedside_cabinet_biomesoplenty_ebony");
        BEDSIDE_CABINET_BIOMESOPLENTY_ETHEREAL = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_ethereal").setRegistryName("bedside_cabinet_biomesoplenty_ethereal");
        BEDSIDE_CABINET_BIOMESOPLENTY_EUCALYPTUS = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_eucalyptus").setRegistryName("bedside_cabinet_biomesoplenty_eucalyptus");
        BEDSIDE_CABINET_BIOMESOPLENTY_FIR = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_fir").setRegistryName("bedside_cabinet_biomesoplenty_fir");
        BEDSIDE_CABINET_BIOMESOPLENTY_HELLBARK = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_hellbark").setRegistryName("bedside_cabinet_biomesoplenty_hellbark");
        BEDSIDE_CABINET_BIOMESOPLENTY_JACARANDA = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_jacaranda").setRegistryName("bedside_cabinet_biomesoplenty_jacaranda");
        BEDSIDE_CABINET_BIOMESOPLENTY_MAGIC = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_magic").setRegistryName("bedside_cabinet_biomesoplenty_magic");
        BEDSIDE_CABINET_BIOMESOPLENTY_MAHOGANY = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_mahogany").setRegistryName("bedside_cabinet_biomesoplenty_mahogany");
        BEDSIDE_CABINET_BIOMESOPLENTY_MANGROVE = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_mangrove").setRegistryName("bedside_cabinet_biomesoplenty_mangrove");
        BEDSIDE_CABINET_BIOMESOPLENTY_PALM = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_palm").setRegistryName("bedside_cabinet_biomesoplenty_palm");
        BEDSIDE_CABINET_BIOMESOPLENTY_PINE = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_pine").setRegistryName("bedside_cabinet_biomesoplenty_pine");
        BEDSIDE_CABINET_BIOMESOPLENTY_REDWOOD = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_redwood").setRegistryName("bedside_cabinet_biomesoplenty_redwood");
        BEDSIDE_CABINET_BIOMESOPLENTY_SACRED_OAK = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_sacred_oak").setRegistryName("bedside_cabinet_biomesoplenty_sacred_oak");
        BEDSIDE_CABINET_BIOMESOPLENTY_UMBRAN = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_umbran").setRegistryName("bedside_cabinet_biomesoplenty_umbran");
        BEDSIDE_CABINET_BIOMESOPLENTY_WILLOW = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_biomesoplenty_willow").setRegistryName("bedside_cabinet_biomesoplenty_willow");

        DESK_BIOMESOPLENTY_CHERRY = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_cherry").setRegistryName("desk_biomesoplenty_cherry");
        DESK_BIOMESOPLENTY_EBONY = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_ebony").setRegistryName("desk_biomesoplenty_ebony");
        DESK_BIOMESOPLENTY_ETHEREAL = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_ethereal").setRegistryName("desk_biomesoplenty_ethereal");
        DESK_BIOMESOPLENTY_EUCALYPTUS = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_eucalyptus").setRegistryName("desk_biomesoplenty_eucalyptus");
        DESK_BIOMESOPLENTY_FIR = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_fir").setRegistryName("desk_biomesoplenty_fir");
        DESK_BIOMESOPLENTY_HELLBARK = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_hellbark").setRegistryName("desk_biomesoplenty_hellbark");
        DESK_BIOMESOPLENTY_JACARANDA = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_jacaranda").setRegistryName("desk_biomesoplenty_jacaranda");
        DESK_BIOMESOPLENTY_MAGIC = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_magic").setRegistryName("desk_biomesoplenty_magic");
        DESK_BIOMESOPLENTY_MAHOGANY = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_mahogany").setRegistryName("desk_biomesoplenty_mahogany");
        DESK_BIOMESOPLENTY_MANGROVE = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_mangrove").setRegistryName("desk_biomesoplenty_mangrove");
        DESK_BIOMESOPLENTY_PALM = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_palm").setRegistryName("desk_biomesoplenty_palm");
        DESK_BIOMESOPLENTY_PINE = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_pine").setRegistryName("desk_biomesoplenty_pine");
        DESK_BIOMESOPLENTY_REDWOOD = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_redwood").setRegistryName("desk_biomesoplenty_redwood");
        DESK_BIOMESOPLENTY_SACRED_OAK = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_sacred_oak").setRegistryName("desk_biomesoplenty_sacred_oak");
        DESK_BIOMESOPLENTY_UMBRAN = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_umbran").setRegistryName("desk_biomesoplenty_umbran");
        DESK_BIOMESOPLENTY_WILLOW = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_biomesoplenty_willow").setRegistryName("desk_biomesoplenty_willow");

        DESK_CABINET_BIOMESOPLENTY_CHERRY = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_cherry").setRegistryName("desk_cabinet_biomesoplenty_cherry");
        DESK_CABINET_BIOMESOPLENTY_EBONY = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_ebony").setRegistryName("desk_cabinet_biomesoplenty_ebony");
        DESK_CABINET_BIOMESOPLENTY_ETHEREAL = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_ethereal").setRegistryName("desk_cabinet_biomesoplenty_ethereal");
        DESK_CABINET_BIOMESOPLENTY_EUCALYPTUS = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_eucalyptus").setRegistryName("desk_cabinet_biomesoplenty_eucalyptus");
        DESK_CABINET_BIOMESOPLENTY_FIR = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_fir").setRegistryName("desk_cabinet_biomesoplenty_fir");
        DESK_CABINET_BIOMESOPLENTY_HELLBARK = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_hellbark").setRegistryName("desk_cabinet_biomesoplenty_hellbark");
        DESK_CABINET_BIOMESOPLENTY_JACARANDA = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_jacaranda").setRegistryName("desk_cabinet_biomesoplenty_jacaranda");
        DESK_CABINET_BIOMESOPLENTY_MAGIC = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_magic").setRegistryName("desk_cabinet_biomesoplenty_magic");
        DESK_CABINET_BIOMESOPLENTY_MAHOGANY = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_mahogany").setRegistryName("desk_cabinet_biomesoplenty_mahogany");
        DESK_CABINET_BIOMESOPLENTY_MANGROVE = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_mangrove").setRegistryName("desk_cabinet_biomesoplenty_mangrove");
        DESK_CABINET_BIOMESOPLENTY_PALM = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_palm").setRegistryName("desk_cabinet_biomesoplenty_palm");
        DESK_CABINET_BIOMESOPLENTY_PINE = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_pine").setRegistryName("desk_cabinet_biomesoplenty_pine");
        DESK_CABINET_BIOMESOPLENTY_REDWOOD = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_redwood").setRegistryName("desk_cabinet_biomesoplenty_redwood");
        DESK_CABINET_BIOMESOPLENTY_SACRED_OAK = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_sacred_oak").setRegistryName("desk_cabinet_biomesoplenty_sacred_oak");
        DESK_CABINET_BIOMESOPLENTY_UMBRAN = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_umbran").setRegistryName("desk_cabinet_biomesoplenty_umbran");
        DESK_CABINET_BIOMESOPLENTY_WILLOW = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_biomesoplenty_willow").setRegistryName("desk_cabinet_biomesoplenty_willow");

        MAIL_BOX_BIOMESOPLENTY_CHERRY = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_cherry").setRegistryName("mail_box_biomesoplenty_cherry");
        MAIL_BOX_BIOMESOPLENTY_EBONY = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_ebony").setRegistryName("mail_box_biomesoplenty_ebony");
        MAIL_BOX_BIOMESOPLENTY_ETHEREAL = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_ethereal").setRegistryName("mail_box_biomesoplenty_ethereal");
        MAIL_BOX_BIOMESOPLENTY_EUCALYPTUS = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_eucalyptus").setRegistryName("mail_box_biomesoplenty_eucalyptus");
        MAIL_BOX_BIOMESOPLENTY_FIR = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_fir").setRegistryName("mail_box_biomesoplenty_fir");
        MAIL_BOX_BIOMESOPLENTY_HELLBARK = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_hellbark").setRegistryName("mail_box_biomesoplenty_hellbark");
        MAIL_BOX_BIOMESOPLENTY_JACARANDA = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_jacaranda").setRegistryName("mail_box_biomesoplenty_jacaranda");
        MAIL_BOX_BIOMESOPLENTY_MAGIC = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_magic").setRegistryName("mail_box_biomesoplenty_magic");
        MAIL_BOX_BIOMESOPLENTY_MAHOGANY = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_mahogany").setRegistryName("mail_box_biomesoplenty_mahogany");
        MAIL_BOX_BIOMESOPLENTY_MANGROVE = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_mangrove").setRegistryName("mail_box_biomesoplenty_mangrove");
        MAIL_BOX_BIOMESOPLENTY_PALM = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_palm").setRegistryName("mail_box_biomesoplenty_palm");
        MAIL_BOX_BIOMESOPLENTY_PINE = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_pine").setRegistryName("mail_box_biomesoplenty_pine");
        MAIL_BOX_BIOMESOPLENTY_REDWOOD = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_redwood").setRegistryName("mail_box_biomesoplenty_redwood");
        MAIL_BOX_BIOMESOPLENTY_SACRED_OAK = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_sacred_oak").setRegistryName("mail_box_biomesoplenty_sacred_oak");
        MAIL_BOX_BIOMESOPLENTY_UMBRAN = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_umbran").setRegistryName("mail_box_biomesoplenty_umbran");
        MAIL_BOX_BIOMESOPLENTY_WILLOW = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_biomesoplenty_willow").setRegistryName("mail_box_biomesoplenty_willow");

        DOOR_BELL_BIOMESOPLENTY_CHERRY = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_cherry").setRegistryName("door_bell_biomesoplenty_cherry");
        DOOR_BELL_BIOMESOPLENTY_EBONY = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_ebony").setRegistryName("door_bell_biomesoplenty_ebony");
        DOOR_BELL_BIOMESOPLENTY_ETHEREAL = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_ethereal").setRegistryName("door_bell_biomesoplenty_ethereal");
        DOOR_BELL_BIOMESOPLENTY_EUCALYPTUS = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_eucalyptus").setRegistryName("door_bell_biomesoplenty_eucalyptus");
        DOOR_BELL_BIOMESOPLENTY_FIR = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_fir").setRegistryName("door_bell_biomesoplenty_fir");
        DOOR_BELL_BIOMESOPLENTY_HELLBARK = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_hellbark").setRegistryName("door_bell_biomesoplenty_hellbark");
        DOOR_BELL_BIOMESOPLENTY_JACARANDA = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_jacaranda").setRegistryName("door_bell_biomesoplenty_jacaranda");
        DOOR_BELL_BIOMESOPLENTY_MAGIC = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_magic").setRegistryName("door_bell_biomesoplenty_magic");
        DOOR_BELL_BIOMESOPLENTY_MAHOGANY = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_mahogany").setRegistryName("door_bell_biomesoplenty_mahogany");
        DOOR_BELL_BIOMESOPLENTY_MANGROVE = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_mangrove").setRegistryName("door_bell_biomesoplenty_mangrove");
        DOOR_BELL_BIOMESOPLENTY_PALM = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_palm").setRegistryName("door_bell_biomesoplenty_palm");
        DOOR_BELL_BIOMESOPLENTY_PINE = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_pine").setRegistryName("door_bell_biomesoplenty_pine");
        DOOR_BELL_BIOMESOPLENTY_REDWOOD = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_redwood").setRegistryName("door_bell_biomesoplenty_redwood");
        DOOR_BELL_BIOMESOPLENTY_SACRED_OAK = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_sacred_oak").setRegistryName("door_bell_biomesoplenty_sacred_oak");
        DOOR_BELL_BIOMESOPLENTY_UMBRAN = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_umbran").setRegistryName("door_bell_biomesoplenty_umbran");
        DOOR_BELL_BIOMESOPLENTY_WILLOW = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_biomesoplenty_willow").setRegistryName("door_bell_biomesoplenty_willow");

        CRATE_BIOMESOPLENTY_CHERRY = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_cherry").setRegistryName("crate_biomesoplenty_cherry");
        CRATE_BIOMESOPLENTY_EBONY = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_ebony").setRegistryName("crate_biomesoplenty_ebony");
        CRATE_BIOMESOPLENTY_ETHEREAL = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_ethereal").setRegistryName("crate_biomesoplenty_ethereal");
        CRATE_BIOMESOPLENTY_EUCALYPTUS = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_eucalyptus").setRegistryName("crate_biomesoplenty_eucalyptus");
        CRATE_BIOMESOPLENTY_FIR = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_fir").setRegistryName("crate_biomesoplenty_fir");
        CRATE_BIOMESOPLENTY_HELLBARK = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_hellbark").setRegistryName("crate_biomesoplenty_hellbark");
        CRATE_BIOMESOPLENTY_JACARANDA = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_jacaranda").setRegistryName("crate_biomesoplenty_jacaranda");
        CRATE_BIOMESOPLENTY_MAGIC = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_magic").setRegistryName("crate_biomesoplenty_magic");
        CRATE_BIOMESOPLENTY_MAHOGANY = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_mahogany").setRegistryName("crate_biomesoplenty_mahogany");
        CRATE_BIOMESOPLENTY_MANGROVE = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_mangrove").setRegistryName("crate_biomesoplenty_mangrove");
        CRATE_BIOMESOPLENTY_PALM = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_palm").setRegistryName("crate_biomesoplenty_palm");
        CRATE_BIOMESOPLENTY_PINE = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_pine").setRegistryName("crate_biomesoplenty_pine");
        CRATE_BIOMESOPLENTY_REDWOOD = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_redwood").setRegistryName("crate_biomesoplenty_redwood");
        CRATE_BIOMESOPLENTY_SACRED_OAK = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_sacred_oak").setRegistryName("crate_biomesoplenty_sacred_oak");
        CRATE_BIOMESOPLENTY_UMBRAN = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_umbran").setRegistryName("crate_biomesoplenty_umbran");
        CRATE_BIOMESOPLENTY_WILLOW = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_biomesoplenty_willow").setRegistryName("crate_biomesoplenty_willow");

        BLINDS_BIOMESOPLENTY_CHERRY = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_cherry_open").setRegistryName("blinds_biomesoplenty_cherry_open");
        BLINDS_BIOMESOPLENTY_EBONY = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_ebony_open").setRegistryName("blinds_biomesoplenty_ebony_open");
        BLINDS_BIOMESOPLENTY_ETHEREAL = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_ethereal_open").setRegistryName("blinds_biomesoplenty_ethereal_open");
        BLINDS_BIOMESOPLENTY_EUCALYPTUS = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_eucalyptus_open").setRegistryName("blinds_biomesoplenty_eucalyptus_open");
        BLINDS_BIOMESOPLENTY_FIR = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_fir_open").setRegistryName("blinds_biomesoplenty_fir_open");
        BLINDS_BIOMESOPLENTY_HELLBARK = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_hellbark_open").setRegistryName("blinds_biomesoplenty_hellbark_open");
        BLINDS_BIOMESOPLENTY_JACARANDA = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_jacaranda_open").setRegistryName("blinds_biomesoplenty_jacaranda_open");
        BLINDS_BIOMESOPLENTY_MAGIC = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_magic_open").setRegistryName("blinds_biomesoplenty_magic_open");
        BLINDS_BIOMESOPLENTY_MAHOGANY = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_mahogany_open").setRegistryName("blinds_biomesoplenty_mahogany_open");
        BLINDS_BIOMESOPLENTY_MANGROVE = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_mangrove_open").setRegistryName("blinds_biomesoplenty_mangrove_open");
        BLINDS_BIOMESOPLENTY_PALM = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_palm_open").setRegistryName("blinds_biomesoplenty_palm_open");
        BLINDS_BIOMESOPLENTY_PINE = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_pine_open").setRegistryName("blinds_biomesoplenty_pine_open");
        BLINDS_BIOMESOPLENTY_REDWOOD = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_redwood_open").setRegistryName("blinds_biomesoplenty_redwood_open");
        BLINDS_BIOMESOPLENTY_SACRED_OAK = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_sacred_oak_open").setRegistryName("blinds_biomesoplenty_sacred_oak_open");
        BLINDS_BIOMESOPLENTY_UMBRAN = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_umbran_open").setRegistryName("blinds_biomesoplenty_umbran_open");
        BLINDS_BIOMESOPLENTY_WILLOW = new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_biomesoplenty_willow_open").setRegistryName("blinds_biomesoplenty_willow_open");


        BLINDS_BIOMESOPLENTY_CHERRY_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_cherry_closed").setRegistryName("blinds_biomesoplenty_cherry_closed");
        BLINDS_BIOMESOPLENTY_EBONY_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_ebony_closed").setRegistryName("blinds_biomesoplenty_ebony_closed");
        BLINDS_BIOMESOPLENTY_ETHEREAL_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_ethereal_closed").setRegistryName("blinds_biomesoplenty_ethereal_closed");
        BLINDS_BIOMESOPLENTY_EUCALYPTUS_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_eucalyptus_closed").setRegistryName("blinds_biomesoplenty_eucalyptus_closed");
        BLINDS_BIOMESOPLENTY_FIR_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_fir_closed").setRegistryName("blinds_biomesoplenty_fir_closed");
        BLINDS_BIOMESOPLENTY_HELLBARK_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_hellbark_closed").setRegistryName("blinds_biomesoplenty_hellbark_closed");
        BLINDS_BIOMESOPLENTY_JACARANDA_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_jacaranda_closed").setRegistryName("blinds_biomesoplenty_jacaranda_closed");
        BLINDS_BIOMESOPLENTY_MAGIC_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_magic_closed").setRegistryName("blinds_biomesoplenty_magic_closed");
        BLINDS_BIOMESOPLENTY_MAHOGANY_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_mahogany_closed").setRegistryName("blinds_biomesoplenty_mahogany_closed");
        BLINDS_BIOMESOPLENTY_MANGROVE_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_mangrove_closed").setRegistryName("blinds_biomesoplenty_mangrove_closed");
        BLINDS_BIOMESOPLENTY_PALM_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_palm_closed").setRegistryName("blinds_biomesoplenty_palm_closed");
        BLINDS_BIOMESOPLENTY_PINE_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_pine_closed").setRegistryName("blinds_biomesoplenty_pine_closed");
        BLINDS_BIOMESOPLENTY_REDWOOD_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_redwood_closed").setRegistryName("blinds_biomesoplenty_redwood_closed");
        BLINDS_BIOMESOPLENTY_SACRED_OAK_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_sacred_oak_closed").setRegistryName("blinds_biomesoplenty_sacred_oak_closed");
        BLINDS_BIOMESOPLENTY_UMBRAN_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_umbran_closed").setRegistryName("blinds_biomesoplenty_umbran_closed");
        BLINDS_BIOMESOPLENTY_WILLOW_CLOSED = new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_biomesoplenty_willow_closed").setRegistryName("blinds_biomesoplenty_willow_closed");

        FENCE_UPGRADED_BIOMESOPLENTY_CHERRY = new BlockUpgradedFence("upgraded_fence_biomesoplenty_cherry");
        FENCE_UPGRADED_BIOMESOPLENTY_EBONY = new BlockUpgradedFence("upgraded_fence_biomesoplenty_ebony");
        FENCE_UPGRADED_BIOMESOPLENTY_ETHEREAL = new BlockUpgradedFence("upgraded_fence_biomesoplenty_ethereal");
        FENCE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS = new BlockUpgradedFence("upgraded_fence_biomesoplenty_eucalyptus");
        FENCE_UPGRADED_BIOMESOPLENTY_FIR = new BlockUpgradedFence("upgraded_fence_biomesoplenty_fir");
        FENCE_UPGRADED_BIOMESOPLENTY_HELLBARK = new BlockUpgradedFence("upgraded_fence_biomesoplenty_hellbark");
        FENCE_UPGRADED_BIOMESOPLENTY_JACARANDA = new BlockUpgradedFence("upgraded_fence_biomesoplenty_jacaranda");
        FENCE_UPGRADED_BIOMESOPLENTY_MAGIC = new BlockUpgradedFence("upgraded_fence_biomesoplenty_magic");
        FENCE_UPGRADED_BIOMESOPLENTY_MAHOGANY = new BlockUpgradedFence("upgraded_fence_biomesoplenty_mahogany");
        FENCE_UPGRADED_BIOMESOPLENTY_MANGROVE = new BlockUpgradedFence("upgraded_fence_biomesoplenty_mangrove");
        FENCE_UPGRADED_BIOMESOPLENTY_PALM = new BlockUpgradedFence("upgraded_fence_biomesoplenty_palm");
        FENCE_UPGRADED_BIOMESOPLENTY_PINE = new BlockUpgradedFence("upgraded_fence_biomesoplenty_pine");
        FENCE_UPGRADED_BIOMESOPLENTY_REDWOOD = new BlockUpgradedFence("upgraded_fence_biomesoplenty_redwood");
        FENCE_UPGRADED_BIOMESOPLENTY_SACRED_OAK = new BlockUpgradedFence("upgraded_fence_biomesoplenty_sacred_oak");
        FENCE_UPGRADED_BIOMESOPLENTY_UMBRAN = new BlockUpgradedFence("upgraded_fence_biomesoplenty_umbran");
        FENCE_UPGRADED_BIOMESOPLENTY_WILLOW = new BlockUpgradedFence("upgraded_fence_biomesoplenty_willow");

        GATE_UPGRADED_BIOMESOPLENTY_CHERRY = new BlockUpgradedGate("upgraded_gate_biomesoplenty_cherry");
        GATE_UPGRADED_BIOMESOPLENTY_EBONY = new BlockUpgradedGate("upgraded_gate_biomesoplenty_ebony");
        GATE_UPGRADED_BIOMESOPLENTY_ETHEREAL = new BlockUpgradedGate("upgraded_gate_biomesoplenty_ethereal");
        GATE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS = new BlockUpgradedGate("upgraded_gate_biomesoplenty_eucalyptus");
        GATE_UPGRADED_BIOMESOPLENTY_FIR = new BlockUpgradedGate("upgraded_gate_biomesoplenty_fir");
        GATE_UPGRADED_BIOMESOPLENTY_HELLBARK = new BlockUpgradedGate("upgraded_gate_biomesoplenty_hellbark");
        GATE_UPGRADED_BIOMESOPLENTY_JACARANDA = new BlockUpgradedGate("upgraded_gate_biomesoplenty_jacaranda");
        GATE_UPGRADED_BIOMESOPLENTY_MAGIC = new BlockUpgradedGate("upgraded_gate_biomesoplenty_magic");
        GATE_UPGRADED_BIOMESOPLENTY_MAHOGANY = new BlockUpgradedGate("upgraded_gate_biomesoplenty_mahogany");
        GATE_UPGRADED_BIOMESOPLENTY_MANGROVE = new BlockUpgradedGate("upgraded_gate_biomesoplenty_mangrove");
        GATE_UPGRADED_BIOMESOPLENTY_PALM = new BlockUpgradedGate("upgraded_gate_biomesoplenty_palm");
        GATE_UPGRADED_BIOMESOPLENTY_PINE = new BlockUpgradedGate("upgraded_gate_biomesoplenty_pine");
        GATE_UPGRADED_BIOMESOPLENTY_REDWOOD = new BlockUpgradedGate("upgraded_gate_biomesoplenty_redwood");
        GATE_UPGRADED_BIOMESOPLENTY_SACRED_OAK = new BlockUpgradedGate("upgraded_gate_biomesoplenty_sacred_oak");
        GATE_UPGRADED_BIOMESOPLENTY_UMBRAN = new BlockUpgradedGate("upgraded_gate_biomesoplenty_umbran");
        GATE_UPGRADED_BIOMESOPLENTY_WILLOW = new BlockUpgradedGate("upgraded_gate_biomesoplenty_willow");

        PARK_BENCH_BIOMESOPLENTY_CHERRY = new BlockParkBench("park_bench_biomesoplenty_cherry");
        PARK_BENCH_BIOMESOPLENTY_EBONY = new BlockParkBench("park_bench_biomesoplenty_ebony");
        PARK_BENCH_BIOMESOPLENTY_ETHEREAL = new BlockParkBench("park_bench_biomesoplenty_ethereal");
        PARK_BENCH_BIOMESOPLENTY_EUCALYPTUS = new BlockParkBench("park_bench_biomesoplenty_eucalyptus");
        PARK_BENCH_BIOMESOPLENTY_FIR = new BlockParkBench("park_bench_biomesoplenty_fir");
        PARK_BENCH_BIOMESOPLENTY_HELLBARK = new BlockParkBench("park_bench_biomesoplenty_hellbark");
        PARK_BENCH_BIOMESOPLENTY_JACARANDA = new BlockParkBench("park_bench_biomesoplenty_jacaranda");
        PARK_BENCH_BIOMESOPLENTY_MAGIC = new BlockParkBench("park_bench_biomesoplenty_magic");
        PARK_BENCH_BIOMESOPLENTY_MAHOGANY = new BlockParkBench("park_bench_biomesoplenty_mahogany");
        PARK_BENCH_BIOMESOPLENTY_MANGROVE = new BlockParkBench("park_bench_biomesoplenty_mangrove");
        PARK_BENCH_BIOMESOPLENTY_PALM = new BlockParkBench("park_bench_biomesoplenty_palm");
        PARK_BENCH_BIOMESOPLENTY_PINE = new BlockParkBench("park_bench_biomesoplenty_pine");
        PARK_BENCH_BIOMESOPLENTY_REDWOOD = new BlockParkBench("park_bench_biomesoplenty_redwood");
        PARK_BENCH_BIOMESOPLENTY_SACRED_OAK = new BlockParkBench("park_bench_biomesoplenty_sacred_oak");
        PARK_BENCH_BIOMESOPLENTY_UMBRAN = new BlockParkBench("park_bench_biomesoplenty_umbran");
        PARK_BENCH_BIOMESOPLENTY_WILLOW = new BlockParkBench("park_bench_biomesoplenty_willow");
    }

    public static void register()
    {
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_CHERRY, new ItemHedge(HEDGE_BIOMESOPLENTY_CHERRY));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_EBONY, new ItemHedge(HEDGE_BIOMESOPLENTY_EBONY));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_ETHEREAL, new ItemHedge(HEDGE_BIOMESOPLENTY_ETHEREAL));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_EUCALYPTUS, new ItemHedge(HEDGE_BIOMESOPLENTY_EUCALYPTUS));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_FIR, new ItemHedge(HEDGE_BIOMESOPLENTY_FIR));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_HELLBARK, new ItemHedge(HEDGE_BIOMESOPLENTY_HELLBARK));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_JACARANDA, new ItemHedge(HEDGE_BIOMESOPLENTY_JACARANDA));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_MAGIC, new ItemHedge(HEDGE_BIOMESOPLENTY_MAGIC));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_MAHOGANY, new ItemHedge(HEDGE_BIOMESOPLENTY_MAHOGANY));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_MANGROVE, new ItemHedge(HEDGE_BIOMESOPLENTY_MANGROVE));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_PALM, new ItemHedge(HEDGE_BIOMESOPLENTY_PALM));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_PINE, new ItemHedge(HEDGE_BIOMESOPLENTY_PINE));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_REDWOOD, new ItemHedge(HEDGE_BIOMESOPLENTY_REDWOOD));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_SACRED_OAK, new ItemHedge(HEDGE_BIOMESOPLENTY_SACRED_OAK));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_UMBRAN, new ItemHedge(HEDGE_BIOMESOPLENTY_UMBRAN));
        FurnitureBlocks.registerBlock(HEDGE_BIOMESOPLENTY_WILLOW, new ItemHedge(HEDGE_BIOMESOPLENTY_WILLOW));

        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(COFFEE_TABLE_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(CHAIR_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(TABLE_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(CABINET_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(BEDSIDE_CABINET_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(DESK_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(DESK_CABINET_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(MAIL_BOX_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(DOOR_BELL_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_CHERRY, new ItemCrate(CRATE_BIOMESOPLENTY_CHERRY));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_EBONY, new ItemCrate(CRATE_BIOMESOPLENTY_EBONY));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_ETHEREAL, new ItemCrate(CRATE_BIOMESOPLENTY_ETHEREAL));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_EUCALYPTUS, new ItemCrate(CRATE_BIOMESOPLENTY_EUCALYPTUS));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_FIR, new ItemCrate(CRATE_BIOMESOPLENTY_FIR));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_HELLBARK, new ItemCrate(CRATE_BIOMESOPLENTY_HELLBARK));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_JACARANDA, new ItemCrate(CRATE_BIOMESOPLENTY_JACARANDA));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_MAGIC, new ItemCrate(CRATE_BIOMESOPLENTY_MAGIC));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_MAHOGANY, new ItemCrate(CRATE_BIOMESOPLENTY_MAHOGANY));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_MANGROVE, new ItemCrate(CRATE_BIOMESOPLENTY_MANGROVE));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_PALM, new ItemCrate(CRATE_BIOMESOPLENTY_PALM));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_PINE, new ItemCrate(CRATE_BIOMESOPLENTY_PINE));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_REDWOOD, new ItemCrate(CRATE_BIOMESOPLENTY_REDWOOD));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_SACRED_OAK, new ItemCrate(CRATE_BIOMESOPLENTY_SACRED_OAK));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_UMBRAN, new ItemCrate(CRATE_BIOMESOPLENTY_UMBRAN));
        FurnitureBlocks.registerBlock(CRATE_BIOMESOPLENTY_WILLOW, new ItemCrate(CRATE_BIOMESOPLENTY_WILLOW));

        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_CHERRY_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_EBONY_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_ETHEREAL_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_EUCALYPTUS_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_FIR_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_HELLBARK_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_JACARANDA_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_MAGIC_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_MAHOGANY_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_MANGROVE_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_PALM_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_PINE_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_REDWOOD_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_SACRED_OAK_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_UMBRAN_CLOSED, null);
        FurnitureBlocks.registerBlock(BLINDS_BIOMESOPLENTY_WILLOW_CLOSED, null);

        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(FENCE_UPGRADED_BIOMESOPLENTY_WILLOW);

        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_CHERRY, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_CHERRY));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_EBONY, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_EBONY));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_ETHEREAL, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_ETHEREAL));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_EUCALYPTUS));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_FIR, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_FIR));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_HELLBARK, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_HELLBARK));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_JACARANDA, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_JACARANDA));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_MAGIC, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_MAGIC));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_MAHOGANY, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_MAHOGANY));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_MANGROVE, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_MANGROVE));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_PALM, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_PALM));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_PINE, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_PINE));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_REDWOOD, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_REDWOOD));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_SACRED_OAK, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_SACRED_OAK));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_UMBRAN, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_UMBRAN));
        FurnitureBlocks.registerBlock(GATE_UPGRADED_BIOMESOPLENTY_WILLOW, new ItemUpgradedGate(GATE_UPGRADED_BIOMESOPLENTY_WILLOW));

        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_CHERRY);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_EBONY);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_ETHEREAL);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_EUCALYPTUS);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_FIR);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_HELLBARK);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_JACARANDA);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_MAGIC);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_MAHOGANY);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_MANGROVE);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_PALM);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_PINE);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_REDWOOD);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_SACRED_OAK);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_UMBRAN);
        FurnitureBlocks.registerBlock(PARK_BENCH_BIOMESOPLENTY_WILLOW);
    }
}
